# Generated by Django 2.2.5 on 2019-09-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190918_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.CharField(default=None, max_length=300),
            preserve_default=False,
        ),
    ]
