# Generated by Django 2.2.5 on 2019-09-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20190918_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='track',
        ),
        migrations.AddField(
            model_name='playlist',
            name='track',
            field=models.ManyToManyField(null=True, to='main_app.Track'),
        ),
    ]
